sudo: required
services:
  - docker

before_install:
  - docker build -t psankhle/react-docker-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true psankhle/react-docker-demo npm run test -- --coverage

